spring:
  datasource:
    url: jdbc:sqlserver://javatechieserver.database.windows.net:1433;database=javatechiedb;user=javatechie@javatechieserver;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: javatechie
    password: muthu@12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect


server:
  port: 9191